### PR TITLE
Add sleep to timing test plugin to avoid sporadically logging 0s

### PR DESCRIPTION
**Pull request by anuraaga**
I guess my hypothesis that 0s is unfeasible is wrong...

https://github.com/tetratelabs/proxy-wasm-go-sdk/actions/runs/3102580430/jobs/5025021859

### CODE REVIEW

**Comment by mathetake** [comment]
so how can we test the lack of `defer`?

**Comment by anuraaga** [comment]
I suppose the plugin doesn't have to be no-op one sec

**Comment by anuraaga** [comment]
Added a small sleep to each function to make sure there is some timing happening

**Review by mathetake — APPROVED** [review]
cool

**Pull request merged**
