### PR TITLE
Fix wrong path size for SetProperty

### LINKED ISSUE #234: bug: SetProperty send wrong path length
## Describe the bug / error

When calling `proxy_set_property` in host call, we pass the wrong `path_size` value.

https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/532d611f21dbc2e94502ca548532a2cc504d80c0/proxywasm/hostcall.go#L568-L571

I think we should pass the value of `len(raw)` instead of the length of the `path` string slice.

## What is your Envoy/Istio version?

I am one of the developers of `wasm-nginx-module` and do not use Envoy and Istio.

## What is the SDK version?

`v0.14.1`

## What is your TinyGo version?

`v0.21.0`

## URL or snippet of your code including Go code and Host debug result

**Go code: `configure[0] = test`  `configure[1] = test.com`**
image

**Host receive result:**
image

### PR DESCRIPTION
**Pull request by bzp2010**
fixes #234

### CODE REVIEW

**Review by mathetake — APPROVED** [review]
LGTM, thanks @bzp2010 for this patch! 🏅 💯

**Comment by bzp2010** [comment]
Hi, @mathetake. Thank you for your quick response and helping the project improve. 

I have a question, when is the next release of this project planned?

**Comment by mathetake** [comment]
@bzp2010 I just released a new tag v0.16.0: https://github.com/tetratelabs/proxy-wasm-go-sdk/releases/tag/v0.16.0 enjoy!

**Comment by bzp2010** [comment]
@mathetake Thanks!! XD

**Pull request merged**
