### PR TITLE
Add the ability to get the current response headers in proxytest

### PR DESCRIPTION
**Pull request by johnkeates**
Hi, this is my first stab at adding the ability to get the current response headers when running tests. At first it seems rather straightforward to add this, but I have been wrong before ;-)

### CODE REVIEW

**Review by mathetake — COMMENTED** [review]
code looks good, but could you modify an example under examples/ directory and actually showcase how this can be used in the unitcase?

**Comment by jcchavezs** [comment]
I think https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/28d009fcffda60ec127ae91006da35f8c0d59482/examples/http_auth_random/main.go or https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/5ef58c62410a10f1dbe9489b0dd3398a35220d25/examples/json_validation/main.go can be the best candidates.

**Comment by mathetake** [comment]
ping @johnkeates

**Comment by johnkeates** [comment]
That would be great, life (👶) is currently getting in the way of me adding the example code right now 🛠️.

**Comment by jcchavezs** [comment]
I've been there. I know the feeling. Enjoy the life, NOTHING is as
important.

tir. 31. mai 2022, 17:07 skrev John Keates ***@***.***>:

**Comment by jcchavezs** [comment]
Merged in https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/295. Thanks @johnkeates

**Pull request closed without merging**
