### PR TITLE
Allow foreign functions to be called with empty byte arrays

### PR DESCRIPTION
**Pull request by jamesmulcahy**

### CODE REVIEW

**Comment by jamesmulcahy** [comment]
Prior to this fix, the included test would panic when indexing into the empty byte array.

```
--- FAIL: TestHostCall_ForeignFunction (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 35 [running]:
testing.tRunner.func1.2({0x11ae4a0, 0xc000156228})
	/usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1212 +0x218
panic({0x11ae4a0, 0xc000156228})
	/usr/local/Cellar/go/1.17.5/libexec/src/runtime/panic.go:1038 +0x215
github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm.CallForeignFunction({0x11bfef7, 0x8}, {0x135d130, 0x0, 0x474})
	/Users/jmulcahy/Projects/proxy-wasm-go-sdk/proxywasm/hostcall.go:587 +0x130
github.com/tetratelabs/proxy-wasm-go-sdk/proxywasm.TestHostCall_ForeignFunction(0x0)
	/Users/jmulcahy/Projects/proxy-wasm-go-sdk/proxywasm/hostcall_test.go:41 +0x6c
testing.tRunner(0xc000105a00, 0x11d20a8)
	/usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/local/Cellar/go/1.17.5/libexec/src/testing/testing.go:1306 +0x35a
```

**Comment by mathetake** [comment]
thanks @jamesmulcahy, could you fix the test? 

```
--- FAIL: TestHostCall_ForeignFunction (0.00s)
    hostcall_test.go:44: 
        	Error Trace:	hostcall_test.go:44
        	Error:      	Not equal: 
        	            	expected: string("")
        	            	actual  : []uint8([]byte(nil))
        	Test:       	TestHostCall_ForeignFunction
```

**Comment by jamesmulcahy** [comment]
@mathetake Whoops, yes - of course.  Fixed in next push!

**Comment by mathetake** [comment]
@jamesmulcahy thank you for the contribution! 💯  🕺

**Pull request merged**
