### PR TITLE
example: using prometheus tags in custom metrics

### LINKED ISSUE #245: Add an example (code and Envoy configuration) to define metrics with tags

### PR DESCRIPTION
**Pull request by mathetake**
Signed-off-by: Takeshi Yoneda <takeshi@tetrate.io>

resolves #245

### CODE REVIEW

**Comment by mathetake** [comment]
@peterj @eitansuez maybe you guys are interested in this ? 😉

**Comment by eitansuez** [comment]
wonderful.  thank you!

**Comment by hochuenw-dd** [comment]
Hi @mathetake, it seems in this example, we are running the wasm VM in each worker thread. Does the SDK automatically aggregate the counter metric if Envoy runs multiple worker threads? If not, do we need to run it in the main thread?
Thanks!

**Comment by mathetake** [comment]
All the metrics are aggregated by Envoy, so you don t need to care
about that

**Comment by hochuenw-dd** [comment]
I see. Thank you for the quick response! @mathetake 
I was reading https://github.com/tetratelabs/proxy-wasm-go-sdk/blob/main/doc/OVERVIEW.md#terminology, 
> Wasm Service is a type of plugins running in a singleton VM (i.e. only one instance exists in the Envoy main thread). It is mainly used for doing some extra work in parallel to Network or Http Filters **_such as aggregating metrics_**, logs, etc. Sometimes, such a singleton VM itself is also called Wasm Service.

It does mention aggregating metrics in Wasm service, I'm curious what is the use case that we might have to aggregate metrics using Wasm Service?

**Pull request merged**
